services:
  backend:
    build: ./backend
    command:
      ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "api.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
        - 8000:8000
        - 5678:5678
    env_file:
        - .env
    volumes:
        - ./backend/api:/app/api