services:
  frontend:
    build:
      context: .
    image: nextjs-dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json