services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    ports:
      - 80:80
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  backend:
    build: ./backend
    ports:
        - $BACKEND_PORT:8000
    restart: always
    env_file:
        - .env
    volumes:
        - ./backend/api:/app/api

  frontend:
    build:
      context: ./frontend
    image: nextjs-dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
        - $ADMINER_PORT:8080